num = int(input("Enter the number: "))
print("The number is even." if num % 2 == 0 else "The number is odd.")
if num > 1:
    print("The number is prime." if all(num % i != 0 for i in range(2, num)) else "The number is composite.")
else: print("The number is neither prime nor composite.")
print("The number is a perfect square." if any(i * i == num for i in range(1, num + 1)) else "The number is not a perfect square.")
print("The number is a perfect cube." if any(i * i * i == num for i in range(1, num + 1)) else "The number is not a perfect cube.")
square_root = next((i for i in range(1, num + 1) if i * i == num), None)
cube_root = next((i for i in range(1, num + 1) if i * i * i == num), None)
print(f"The number's square root is: {square_root}" if square_root else "The number's square root is not an integer.")
print(f"The number's cube root is: {cube_root}" if cube_root else "The number's cube root is not an integer.")
print(f"The number's square is: {num ** 2}, cube is: {num ** 3}")
sum_of_powers = sum(int(digit) ** len(str(num)) for digit in str(num))
print("The number is an Armstrong number." if sum_of_powers == num else "The number is not an Armstrong number.")